/*
 * Copyright (c) 2026 Pachli Association
 *
 * This file is a part of Pachli.
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation; either version 3 of the
 * License, or (at your option) any later version.
 *
 * Pachli is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Pachli; if not,
 * see <http://www.gnu.org/licenses>.
 */

package app.pachli.core.designsystem.theme
import androidx.compose.ui.graphics.Color

// Material colour definitions.

internal val primaryLight = Color(0xFF00C853)
internal val onPrimaryLight = Color(0xFF000000)
internal val primaryContainerLight = Color(0xFF003D1E)
internal val onPrimaryContainerLight = Color(0xFF5EE89C)
internal val secondaryLight = Color(0xFF888888)
internal val onSecondaryLight = Color(0xFF000000)
internal val secondaryContainerLight = Color(0xFF1A1A1A)
internal val onSecondaryContainerLight = Color(0xFFFFFFFF)
internal val tertiaryLight = Color(0xFF888888)
internal val onTertiaryLight = Color(0xFF000000)
internal val tertiaryContainerLight = Color(0xFF1A1A1A)
internal val onTertiaryContainerLight = Color(0xFFFFFFFF)
internal val errorLight = Color(0xFFFF0000)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFF660000)
internal val onErrorContainerLight = Color(0xFFFFFFFF)
internal val backgroundLight = Color(0xFF000000)
internal val onBackgroundLight = Color(0xFFFFFFFF)
internal val surfaceLight = Color(0xFF0A0A0A)
internal val onSurfaceLight = Color(0xFFFFFFFF)
internal val surfaceVariantLight = Color(0xFF1A1A1A)
internal val onSurfaceVariantLight = Color(0xFFFFFFFF)
internal val outlineLight = Color(0xFF888888)
internal val outlineVariantLight = Color(0xFF333333)
internal val scrimLight = Color(0xFFFFFFFF)
internal val inverseSurfaceLight = Color(0xFF0A0A0A)
internal val inverseOnSurfaceLight = Color(0xFF0A0A0A)
internal val inversePrimaryLight = Color(0xFF00C853)
internal val surfaceDimLight = Color(0xFF0A0A0A)
internal val surfaceBrightLight = Color(0xFF1A1A1A)
internal val surfaceContainerLowestLight = Color(0xFF000000)
internal val surfaceContainerLowLight = Color(0xFF050505)
internal val surfaceContainerLight = Color(0xFF1A1A1A)
internal val surfaceContainerHighLight = Color(0xFF1A1A1A)
internal val surfaceContainerHighestLight = Color(0xFF333333)

internal val primaryLightMediumContrast = Color(0xFF00C853)
internal val onPrimaryLightMediumContrast = Color(0xFF000000)
internal val primaryContainerLightMediumContrast = Color(0xFF003D1E)
internal val onPrimaryContainerLightMediumContrast = Color(0xFF5EE89C)
internal val secondaryLightMediumContrast = Color(0xFF888888)
internal val onSecondaryLightMediumContrast = Color(0xFF000000)
internal val secondaryContainerLightMediumContrast = Color(0xFF1A1A1A)
internal val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryLightMediumContrast = Color(0xFF888888)
internal val onTertiaryLightMediumContrast = Color(0xFF000000)
internal val tertiaryContainerLightMediumContrast = Color(0xFF1A1A1A)
internal val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val errorLightMediumContrast = Color(0xFFFF0000)
internal val onErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val errorContainerLightMediumContrast = Color(0xFF660000)
internal val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val backgroundLightMediumContrast = Color(0xFF000000)
internal val onBackgroundLightMediumContrast = Color(0xFFFFFFFF)
internal val surfaceLightMediumContrast = Color(0xFF0A0A0A)
internal val onSurfaceLightMediumContrast = Color(0xFFFFFFFF)
internal val surfaceVariantLightMediumContrast = Color(0xFF1A1A1A)
internal val onSurfaceVariantLightMediumContrast = Color(0xFFFFFFFF)
internal val outlineLightMediumContrast = Color(0xFF888888)
internal val outlineVariantLightMediumContrast = Color(0xFF333333)
internal val scrimLightMediumContrast = Color(0xFFFFFFFF)
internal val inverseSurfaceLightMediumContrast = Color(0xFF0A0A0A)
internal val inverseOnSurfaceLightMediumContrast = Color(0xFF0A0A0A)
internal val inversePrimaryLightMediumContrast = Color(0xFF00C853)
internal val surfaceDimLightMediumContrast = Color(0xFF0A0A0A)
internal val surfaceBrightLightMediumContrast = Color(0xFF1A1A1A)
internal val surfaceContainerLowestLightMediumContrast = Color(0xFF000000)
internal val surfaceContainerLowLightMediumContrast = Color(0xFF050505)
internal val surfaceContainerLightMediumContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighLightMediumContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighestLightMediumContrast = Color(0xFF333333)

internal val primaryLightHighContrast = Color(0xFF00C853)
internal val onPrimaryLightHighContrast = Color(0xFF000000)
internal val primaryContainerLightHighContrast = Color(0xFF003D1E)
internal val onPrimaryContainerLightHighContrast = Color(0xFF5EE89C)
internal val secondaryLightHighContrast = Color(0xFF888888)
internal val onSecondaryLightHighContrast = Color(0xFF000000)
internal val secondaryContainerLightHighContrast = Color(0xFF1A1A1A)
internal val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryLightHighContrast = Color(0xFF888888)
internal val onTertiaryLightHighContrast = Color(0xFF000000)
internal val tertiaryContainerLightHighContrast = Color(0xFF1A1A1A)
internal val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val errorLightHighContrast = Color(0xFFFF0000)
internal val onErrorLightHighContrast = Color(0xFFFFFFFF)
internal val errorContainerLightHighContrast = Color(0xFF660000)
internal val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val backgroundLightHighContrast = Color(0xFF000000)
internal val onBackgroundLightHighContrast = Color(0xFFFFFFFF)
internal val surfaceLightHighContrast = Color(0xFF0A0A0A)
internal val onSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val surfaceVariantLightHighContrast = Color(0xFF1A1A1A)
internal val onSurfaceVariantLightHighContrast = Color(0xFFFFFFFF)
internal val outlineLightHighContrast = Color(0xFF888888)
internal val outlineVariantLightHighContrast = Color(0xFF333333)
internal val scrimLightHighContrast = Color(0xFFFFFFFF)
internal val inverseSurfaceLightHighContrast = Color(0xFF0A0A0A)
internal val inverseOnSurfaceLightHighContrast = Color(0xFF0A0A0A)
internal val inversePrimaryLightHighContrast = Color(0xFF00C853)
internal val surfaceDimLightHighContrast = Color(0xFF0A0A0A)
internal val surfaceBrightLightHighContrast = Color(0xFF1A1A1A)
internal val surfaceContainerLowestLightHighContrast = Color(0xFF000000)
internal val surfaceContainerLowLightHighContrast = Color(0xFF050505)
internal val surfaceContainerLightHighContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighLightHighContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighestLightHighContrast = Color(0xFF333333)

internal val primaryDark = Color(0xFF00C853)
internal val onPrimaryDark = Color(0xFF000000)
internal val primaryContainerDark = Color(0xFF003D1E)
internal val onPrimaryContainerDark = Color(0xFF5EE89C)
internal val secondaryDark = Color(0xFF888888)
internal val onSecondaryDark = Color(0xFF000000)
internal val secondaryContainerDark = Color(0xFF1A1A1A)
internal val onSecondaryContainerDark = Color(0xFFFFFFFF)
internal val tertiaryDark = Color(0xFF888888)
internal val onTertiaryDark = Color(0xFF000000)
internal val tertiaryContainerDark = Color(0xFF1A1A1A)
internal val onTertiaryContainerDark = Color(0xFFFFFFFF)
internal val errorDark = Color(0xFFFF0000)
internal val onErrorDark = Color(0xFFFFFFFF)
internal val errorContainerDark = Color(0xFF660000)
internal val onErrorContainerDark = Color(0xFFFFFFFF)
internal val backgroundDark = Color(0xFF000000)
internal val onBackgroundDark = Color(0xFFFFFFFF)
internal val surfaceDark = Color(0xFF0A0A0A)
internal val onSurfaceDark = Color(0xFFFFFFFF)
internal val surfaceVariantDark = Color(0xFF1A1A1A)
internal val onSurfaceVariantDark = Color(0xFFFFFFFF)
internal val outlineDark = Color(0xFF888888)
internal val outlineVariantDark = Color(0xFF333333)
internal val scrimDark = Color(0xFFFFFFFF)
internal val inverseSurfaceDark = Color(0xFF0A0A0A)
internal val inverseOnSurfaceDark = Color(0xFF0A0A0A)
internal val inversePrimaryDark = Color(0xFF00C853)
internal val surfaceDimDark = Color(0xFF0A0A0A)
internal val surfaceBrightDark = Color(0xFF1A1A1A)
internal val surfaceContainerLowestDark = Color(0xFF000000)
internal val surfaceContainerLowDark = Color(0xFF050505)
internal val surfaceContainerDark = Color(0xFF1A1A1A)
internal val surfaceContainerHighDark = Color(0xFF1A1A1A)
internal val surfaceContainerHighestDark = Color(0xFF333333)

internal val primaryDarkMediumContrast = Color(0xFF00C853)
internal val onPrimaryDarkMediumContrast = Color(0xFF000000)
internal val primaryContainerDarkMediumContrast = Color(0xFF003D1E)
internal val onPrimaryContainerDarkMediumContrast = Color(0xFF5EE89C)
internal val secondaryDarkMediumContrast = Color(0xFF888888)
internal val onSecondaryDarkMediumContrast = Color(0xFF000000)
internal val secondaryContainerDarkMediumContrast = Color(0xFF1A1A1A)
internal val onSecondaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryDarkMediumContrast = Color(0xFF888888)
internal val onTertiaryDarkMediumContrast = Color(0xFF000000)
internal val tertiaryContainerDarkMediumContrast = Color(0xFF1A1A1A)
internal val onTertiaryContainerDarkMediumContrast = Color(0xFFFFFFFF)
internal val errorDarkMediumContrast = Color(0xFFFF0000)
internal val onErrorDarkMediumContrast = Color(0xFFFFFFFF)
internal val errorContainerDarkMediumContrast = Color(0xFF660000)
internal val onErrorContainerDarkMediumContrast = Color(0xFFFFFFFF)
internal val backgroundDarkMediumContrast = Color(0xFF000000)
internal val onBackgroundDarkMediumContrast = Color(0xFFFFFFFF)
internal val surfaceDarkMediumContrast = Color(0xFF0A0A0A)
internal val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkMediumContrast = Color(0xFF1A1A1A)
internal val onSurfaceVariantDarkMediumContrast = Color(0xFFFFFFFF)
internal val outlineDarkMediumContrast = Color(0xFF888888)
internal val outlineVariantDarkMediumContrast = Color(0xFF333333)
internal val scrimDarkMediumContrast = Color(0xFFFFFFFF)
internal val inverseSurfaceDarkMediumContrast = Color(0xFF0A0A0A)
internal val inverseOnSurfaceDarkMediumContrast = Color(0xFF0A0A0A)
internal val inversePrimaryDarkMediumContrast = Color(0xFF00C853)
internal val surfaceDimDarkMediumContrast = Color(0xFF0A0A0A)
internal val surfaceBrightDarkMediumContrast = Color(0xFF1A1A1A)
internal val surfaceContainerLowestDarkMediumContrast = Color(0xFF000000)
internal val surfaceContainerLowDarkMediumContrast = Color(0xFF050505)
internal val surfaceContainerDarkMediumContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighDarkMediumContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighestDarkMediumContrast = Color(0xFF333333)

internal val primaryDarkHighContrast = Color(0xFF00C853)
internal val onPrimaryDarkHighContrast = Color(0xFF000000)
internal val primaryContainerDarkHighContrast = Color(0xFF003D1E)
internal val onPrimaryContainerDarkHighContrast = Color(0xFF5EE89C)
internal val secondaryDarkHighContrast = Color(0xFF888888)
internal val onSecondaryDarkHighContrast = Color(0xFF000000)
internal val secondaryContainerDarkHighContrast = Color(0xFF1A1A1A)
internal val onSecondaryContainerDarkHighContrast = Color(0xFFFFFFFF)
internal val tertiaryDarkHighContrast = Color(0xFF888888)
internal val onTertiaryDarkHighContrast = Color(0xFF000000)
internal val tertiaryContainerDarkHighContrast = Color(0xFF1A1A1A)
internal val onTertiaryContainerDarkHighContrast = Color(0xFFFFFFFF)
internal val errorDarkHighContrast = Color(0xFFFF0000)
internal val onErrorDarkHighContrast = Color(0xFFFFFFFF)
internal val errorContainerDarkHighContrast = Color(0xFF660000)
internal val onErrorContainerDarkHighContrast = Color(0xFFFFFFFF)
internal val backgroundDarkHighContrast = Color(0xFF000000)
internal val onBackgroundDarkHighContrast = Color(0xFFFFFFFF)
internal val surfaceDarkHighContrast = Color(0xFF0A0A0A)
internal val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkHighContrast = Color(0xFF1A1A1A)
internal val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val outlineDarkHighContrast = Color(0xFF888888)
internal val outlineVariantDarkHighContrast = Color(0xFF333333)
internal val scrimDarkHighContrast = Color(0xFFFFFFFF)
internal val inverseSurfaceDarkHighContrast = Color(0xFF0A0A0A)
internal val inverseOnSurfaceDarkHighContrast = Color(0xFF0A0A0A)
internal val inversePrimaryDarkHighContrast = Color(0xFF00C853)
internal val surfaceDimDarkHighContrast = Color(0xFF0A0A0A)
internal val surfaceBrightDarkHighContrast = Color(0xFF1A1A1A)
internal val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val surfaceContainerLowDarkHighContrast = Color(0xFF050505)
internal val surfaceContainerDarkHighContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighDarkHighContrast = Color(0xFF1A1A1A)
internal val surfaceContainerHighestDarkHighContrast = Color(0xFF333333)

internal val onPrimaryBlack = Color.Black
internal val backgroundBlack = Color.Black
internal val surfaceBlack = tuskyGrey10
internal val surfaceContainerLowestBlack = tuskyGrey10
internal val surfaceContainerLowBlack = tuskyGrey10
internal val surfaceContainerBlack = tuskyGrey10
internal val surfaceContainerHighBlack = tuskyGrey10
internal val surfaceContainerHighestBlack = tuskyGrey10
